-- Active: 1707101283495@@127.0.0.1@3306@sesac
SHOW TABLES;
USE DOBONG;
DESC USER;
DROP TABLE USER;
TRUNCATE TABLE USER;
CREATE TABLE USER(
    USERCODE INT AUTO_INCREMENT PRIMARY KEY,
    ID VARCHAR(255) NOT NULL,
    PW VARCHAR(255) NOT NULL,
    NAME VARCHAR(15) NOT NULL
);

SHOW TABLES;
SELECT * FROM MYSQL.USER;
SELECT * FROM USER;