SHOW DATABASES;

USE DOBONG;

-- 실습1
SHOW TABLES;
CREATE TABLE MEMBERS(
    ID VARCHAR(20) NOT NULL PRIMARY KEY,
    NAME VARCHAR(5) NOT NULL,
    AGE INT,
    GENDER VARCHAR(2) NOT NULL,
    EMAIL VARCHAR(50),
    PROMOTION VARCHAR(2) DEFAULT 'X'
);
DESC MEMBERS;
-- 실습2
ALTER TABLE MEMBERS MODIFY ID VARCHAR(10);
ALTER TABLE MEMBERS DROP AGE;
ALTER TABLE MEMBERS ADD INTEREST VARCHAR(100);

-- 실습3
CREATE TABLE USER(
    ID VARCHAR(10) PRIMARY KEY,
    PW VARCHAR(20) NOT NULL,
    NAME VARCHAR(5) NOT NULL,
    GENDER ENUM('F', 'M', '') DEFAULT '',
    BIRTHDAY DATE NOT NULL,
    AGE INT(3) NOT NULL DEFAULT 0 
);
DESC USER;

-- 실습4
INSERT INTO USER (ID, PW, NAME, GENDER, BIRTHDAY, AGE) VALUES('hong1234', '8o4bkg', '홍길동', 'M', '1990-01-31', 33);
INSERT INTO USER (ID, PW, NAME, GENDER, BIRTHDAY, AGE) VALUES('sexysung', '87awjkdf', '성춘향', 'F', '1992-03-31', 31);
INSERT INTO USER (ID, PW, NAME, GENDER, BIRTHDAY, AGE) VALUES('power70', 'qxur8sda', '변사또', 'M', '1970-05-02', 53);
INSERT INTO USER (ID, PW, NAME, GENDER, BIRTHDAY, AGE) VALUES('hanjo', 'jk48fn4', '한조', 'M', '1984-10-18', 39);
INSERT INTO USER (ID, PW, NAME, GENDER, BIRTHDAY, AGE) VALUES('widowmaker', '38ewifh3', '위도우', 'F', '1976-06-27', 47);
INSERT INTO USER (ID, PW, NAME, GENDER, BIRTHDAY, AGE) VALUES('dvadva', 'k3f3ah', '송하나', 'F', '2001-06-03', 22);
INSERT INTO USER (ID, PW, NAME, GENDER, BIRTHDAY, AGE) VALUES('jungkrat', '4ifha7f', '정크랫', 'M', '1999-11-11', 24);

SELECT * FROM USER;

-- 실습5
SELECT * FROM USER ORDER BY BIRTHDAY;
SELECT * FROM USER WHERE GENDER='M' ORDER BY NAME DESC;
SELECT ID, NAME FROM USER WHERE BIRTHDAY LIKE '199%';
SELECT * FROM USER WHERE BIRTHDAY LIKE '%-06-%' ORDER BY BIRTHDAY;
-- DATE 함수 사용
-- SELECT * FROM USER WHERE MONTH(BIRTHDAY)=6 ORDER BY BIRTHDAY;
SELECT * FROM USER WHERE GENDER='M' AND BIRTHDAY LIKE '197%';
SELECT * FROM USER ORDER BY AGE DESC LIMIT 3;
SELECT * FROM USER WHERE AGE BETWEEN 25 AND 50;
UPDATE USER SET PW='12345678' WHERE ID='hong1234';
DELETE FROM USER WHERE ID='jungkrat';

SELECT * FROM USER;

/* 
    QUERY 순서
    SELECT
    FROM
    WHERE
    GROUP BY
    HAVING
    ORDER BY
    LIMIT
 */